# Generated by Django 3.2.8 on 2022-05-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='hard',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='plants',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
