# Generated by Django 3.2.8 on 2022-05-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20220516_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='add',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='soil',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
