# Generated by Django 3.2.8 on 2022-05-30 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_alter_plants_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantTasks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500, null=True)),
                ('type', models.CharField(max_length=100)),
                ('duedate', models.DateField(null=True)),
                ('actualdate', models.DateField(null=True)),
                ('done', models.BooleanField(default=False)),
                ('plantid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.plants')),
            ],
        ),
    ]
